AWSTemplateFormatVersion: "2010-09-09"
Description: Test cfn Template

Resources:
  cfnVpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "192.168.0.0/16"
      Tags:
        - Key: "Name"
          Value: "cfn-vpc"
  cfnSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "192.168.1.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "cfn-subnet"
      VpcId: !Ref cfnVpc
